name: Copier

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/copier-update.yml
  schedule:
    - cron: '3 16 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        update-package-json: [true, false]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.14'
      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
      - name: Run copier update
        run: uvx copier@latest update --trust --vcs-ref main --exclude src --exclude test $([ "${{ matrix['update-package-json'] }}" = "true" ] || echo "--exclude package.json") --defaults || true
      - name: Apply incoming changes
        run: |
          git diff --name-only --diff-filter=U -z | while IFS= read -r -d '' file; do
            git checkout --theirs -- "$file"
          done
          git add -A
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
        with:
          branch: chore/copier-auto-update-${{ matrix['update-package-json'] && 'with-package-json' || 'without-package-json' }}
          title: |
            chore(deps): run `copier update` ${{ matrix['update-package-json'] && 'with package.json' || 'without package.json' }}
          commit-message: 'chore(deps): run `copier update`'
          token: ${{ secrets.GH_PAT }}

  recopy:
    name: Recopy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        update-package-json: [true, false]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.14'
      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
      - name: Run copier recopy
        run: uvx copier@latest recopy --trust --vcs-ref main --exclude src --exclude test $([ "${{ matrix['update-package-json'] }}" = "true" ] || echo "--exclude package.json") --defaults --overwrite || true
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
        with:
          branch: chore/copier-auto-recopy-${{ matrix['update-package-json'] && 'with-package-json' || 'without-package-json' }}
          title: |
            chore(deps): run `copier recopy` ${{ matrix['update-package-json'] && 'with package.json' || 'without package.json' }}
          commit-message: 'chore(deps): run `copier recopy`'
          token: ${{ secrets.GH_PAT }}
