name: Copier

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/copier-update.yml
  schedule:
    - cron: '3 16 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.14'
      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
      - name: Run copier update
        run: uvx --upgrade copier update --trust --vcs-ref main --exclude src --exclude test --exclude package.json --defaults
      - name: Add changes
        run: git add -A
      - name: Delete remote branch
        run: git push origin --delete chore/copier-auto-update || true
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
        with:
          branch: chore/copier-auto-update
          title: 'chore(deps): run `copier update`'
          commit-message: 'chore(deps): run `copier update`'
          token: ${{ secrets.GH_PAT }}

  recopy:
    name: Recopy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.14'
      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
      - name: Run copier recopy
        run: uvx --upgrade copier recopy --trust --vcs-ref main --exclude src --exclude test --exclude package.json --defaults --overwrite
      - name: Delete remote branch
        run: git push origin --delete chore/copier-auto-recopy || true
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
        with:
          branch: chore/copier-auto-recopy
          title: 'chore(deps): run `copier recopy`'
          commit-message: 'chore(deps): run `copier recopy`'
          token: ${{ secrets.GH_PAT }}
